[package]
name = "bevy-multiplayer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.15.0"
bevy = "0.5.0"
serde = "1.0.127"
rand = "0.8.4"
crossbeam-channel = "0.5.1"